%------------------------------------------------------------------------------%
% Simulate penetration depth for a given laser energy.
%------------------------------------------------------------------------------%

%% Parameter Definition
distArr = 7.5:15:12000;
eleAngle = 0;
laserWL = 1030;
pulseEn = 0.15;
FWHMs = 3;
runSimulation = true;
fogType = 'sea-fog-none';

%% Signal Simulation
height = distArr * sin(eleAngle / 180 * pi);
[mBsc, mExt] = MolModel(height, laserWL, 'meteor', 'standard_atmosphere');
[aBsc, aExt] = AerModel(height, 'scene', 'marine-moderate');
[fBsc, fExt] = SeaFogModel(distArr, laserWL, 'scene', fogType, 'distLayerFront', 0, 'distLayerBack', 10000);
dataSim = LISMO_Model(distArr, 'tBsc', mBsc + aBsc + fBsc, ...
                               'tExt', mExt + aExt + fExt, ...
                               'eleAngle', eleAngle, ...
                               'laserWL', laserWL, ...
                               'pulseEn', pulseEn, ...
                               'accShots', 25000, ...
                               'PB', 0, ...
                               'FWHM', 3, ...
                               'visible', 'on', ...
                               'ylim', [0, 4]);